### ISSUE TITLE
Unexpected error message using <xsl:strip-space>

### ISSUE THREAD

**Issue by jkhile** [DeltaXML/vscode-xslt-tokenizer#103] opened 2022-08-27 14:46 UTC
Unexpected error message using <xsl:strip-space>

Stylesheet has 
```xslt
<xsl:strip-space elements="book Root Story"/>
```
at the top level but an error is displayed in the editor: 
> ATTRIBUTE: value 'book Root Story' is invalid for attribute 'elements' - expected values: *

**Comment by pgfearo** [comment] 2022-08-30 05:20
Thank you for reporting this issue. This bug is associated with the `xsl:nametests` type in the schema and affects the `xsl:strip-space` and `xsl:preserve-space` instructions. 

The linter now checks for a space-separated list of valid element names or the '*' character. Previously it only accepted the '*' character as being valid.

The issue is now fixed.

**Closed by pgfearo** 2022-08-30 05:20 UTC
