### ISSUE TITLE
'Follow link' on href of xsl:import does not work

### ISSUE THREAD

**Issue by eluija** [DeltaXML/vscode-xslt-tokenizer#42] opened 2021-02-18 07:24 UTC
I have attached a zip of a simply project. master.xslt which includes properties.xlst (in the same folder)
If I Ctrl+Click on the href, I get an error message: 

![image](https://user-images.githubusercontent.com/54580336/108320093-a0c82f00-71c2-11eb-8c63-b8b37bf0ea76.png)
 
The path in the error message is the correct path to the file.

[test.zip](https://github.com/DeltaXML/vscode-xslt-tokenizer/files/6000926/test.zip)

**Comment by pgfearo** [comment] 2021-02-23 20:16
Thanks for reporting this issue. I'll provide an update as soon as I've investigated further.

**Comment by pgfearo** [comment] 2021-02-23 20:27
Just to confirm, I can reproduce this issue on my test Windows machine. The path seems to be treated as a URI when being resolved from a relative path.

**Comment by pgfearo** [comment] 2021-02-24 06:59
The problem was that the file path string was not being correctly converted to a URI string before being parsed to a URI type. This issue has now been fixed in [Release v0.2.2](https://github.com/DeltaXML/vscode-xslt-tokenizer/wiki/Release-Notes#release-022)

**Closed by pgfearo** 2021-02-24 06:59 UTC
